name: Pytest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://akaisercoding/abl_scm_venv:latest

    steps:
      - uses: actions/checkout@v3
      - name: Test with pytest
        run: |
          cd shared
          python3 -m pytest